import {getSeasonalData} from "./seasonalProductsAndIngredients";

/**
 * Information pertaining to every item on the menu, including the ingredients in the dish and modifications that can be made to them. Also includes price and a picture.
 * @type {[{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},null,null,null,null]}
 */
export const mealItems = [
    { name: 'Chick-fil-A Sandwich Meal', price: 8.55, image: 'images/meals/CFA_Chicken_Sandwich_Meal.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}] , ingredients: ["Breading", "Chicken Breasts", "White Buns", "Butter", "Pickles", "Sea Salt", "Medium Fry Containers" ,"Waffle-Cut Potatoes", "Medium Red Cups", "Lids", "Bags", "Napkins", "Receipt", "Sandwich Containers", "Straw", "Ice"], custom: ["Butter", "Pickles", "Tomatoes", "Lettuce", "Bacon","American Cheese", "Colby Jack Cheese", "Pepper Jack Cheese" , "Sea Salt"]},
    { name: 'Chick-fil-A Deluxe Meal', price: 9.25, image: 'images/meals/CFA_Deluxe_Sandwich_Meal.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}] , ingredients: ["Breading", "Chicken Breasts", "White Buns", "Butter", "Pickles", "Lettuce", "Tomatoes", "American Cheese", "Sea Salt", "Medium Fry Containers" ,"Waffle-Cut Potatoes", "Medium Red Cups", "Lids", "Bags", "Napkins", "Receipt", "Sandwich Containers", "Straw", "Ice"], custom: ["Butter", "Pickles", "Lettuce", "Tomatoes","Bacon","American Cheese", "Colby Jack Cheese", "Pepper Jack Cheese", "Sea Salt"]},
    { name: 'Chick-fil-A Spicy Chicken Sandwich Meal', price: 8.95, image: 'images/meals/CFA_Spicy_Chicken_Sandwich_Meal.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}] , ingredients: ["Breading", "Spicy Seasoning", "Chicken Breasts", "White Buns", "Butter", "Pickles", "Sea Salt", "Medium Fry Containers" ,"Waffle-Cut Potatoes", "Medium Red Cups", "Lids", "Bags", "Napkins", "Receipt", "Sandwich Containers", "Straw", "Ice"], custom: ["Butter", "Pickles", "Lettuce", "Tomatoes","Bacon","American Cheese", "Colby Jack Cheese", "Pepper Jack Cheese", "Sea Salt"] },
    { name: 'Spicy Chicken Sandwich Deluxe Meal', price: 9.65, image: 'images/meals/CFA_Spicy_Deluxe_Sandwich_Meal.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Breading", "Spicy Seasoning", "Chicken Breasts", "White Buns", "Butter", "Pickles", "Lettuce", "Tomatoes", "Pepper Jack Cheese", "Sea Salt", "Medium Fry Containers" ,"Waffle-Cut Potatoes", "Medium Red Cups", "Lids", "Bags", "Napkins", "Receipt", "Sandwich Containers", "Straw", "Ice"], custom: ["Butter", "Pickles", "Lettuce", "Tomatoes","Bacon","American Cheese", "Colby Jack Cheese", "Pepper Jack Cheese", "Sea Salt"]},
    { name: 'Chick-fil-A Nuggets 8-Piece Meal', price: 8.55, image: 'images/meals/CFA_Chicken_Nuggets_8-Piece_Meal.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Breading", "Chicken Breasts", "Sea Salt", "Medium Fry Containers" ,"Waffle-Cut Potatoes", "Medium Red Cups", "Lids", "Bags", "Napkins", "Receipt", "Sandwich Containers", "Straw", "Ice"], custom: ["Ketchup", "Chick-fil-A Sauce", "Polynesian Sauce","Barbeque Sauce", "Honey Mustard Sauce" , "Garden Herb Ranch Sauce'" , "Sweet and Spicy Sriracha Sauce" ,"Honey Roasted BBQ Sauce"]},
    { name: 'Chick-fil-A Nuggets 12-Piece Meal', price: 10.55, image: 'images/meals/CFA_Chicken_Nuggets_12-Piece_Meal.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Breading", "Chicken Breasts", "Sea Salt", "Medium Fry Containers" ,"Waffle-Cut Potatoes", "Medium Red Cups", "Lids", "Bags", "Napkins", "Receipt", "Sandwich Containers", "Straw", "Ice"], custom: ["Ketchup", "Chick-fil-A Sauce", "Polynesian Sauce","Barbeque Sauce", "Honey Mustard Sauce" , "Garden Herb Ranch Sauce'" , "Sweet and Spicy Sriracha Sauce" ,"Honey Roasted BBQ Sauce"]},
    { name: 'Grilled Nuggets 8-Piece Meal', price: 9.55, image: 'images/meals/CFA_Grilled_Chicken_Nuggets_8-Piece_Meal.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Marination", "Chicken Breasts", "Sea Salt", "Medium Fry Containers" ,"Waffle-Cut Potatoes", "Medium Red Cups", "Lids", "Bags", "Napkins", "Receipt", "Sandwich Containers", "Straw", "Ice"], custom: ["Ketchup", "Chick-fil-A Sauce", "Polynesian Sauce","Barbeque Sauce", "Honey Mustard Sauce" , "Garden Herb Ranch Sauce'" , "Sweet and Spicy Sriracha Sauce" ,"Honey Roasted BBQ Sauce"]},
    { name: 'Grilled Nuggets 12-Piece Meal', price: 11.99, image: 'images/meals/CFA_Grilled_Chicken_Nuggets_12-Piece_Meal.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Marination", "Chicken Breasts", "Sea Salt", "Medium Fry Containers" ,"Waffle-Cut Potatoes", "Medium Red Cups", "Lids", "Bags", "Napkins", "Receipt", "Sandwich Containers", "Straw", "Ice"], custom: ["Ketchup", "Chick-fil-A Sauce", "Polynesian Sauce","Barbeque Sauce", "Honey Mustard Sauce" , "Garden Herb Ranch Sauce'" , "Sweet and Spicy Sriracha Sauce" ,"Honey Roasted BBQ Sauce"]},
    { name: 'Grilled Chicken Sandwich Meal', price: 10.29, image: 'images/meals/CFA_Grilled_Chicken_Sandwich_Meal.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Chicken Breasts", "White Buns", "Butter", "Pickles", "Sea Salt", "Medium Fry Containers" ,"Waffle-Cut Potatoes", "Medium Red Cups", "Lids", "Bags", "Napkins", "Receipt", "Sandwich Containers", "Straw", "Ice"], custom: ["Butter", "Pickles", "Lettuce", "Tomatoes","Bacon","American Cheese", "Colby Jack Cheese", "Pepper Jack Cheese", "Sea Salt"]  },
];

/**
 * Information pertaining to every item on the menu, including the ingredients in the dish and modifications that can be made to them. Also includes price and a picture.
 * @type {[{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},null,null,null,null]}
 */
export const entreeItems = [
    { name: 'Chick-fil-A Sandwich', price: 4.85, image: 'images/entrees/CFA_Chicken_Sandwich.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}] , ingredients: ["Breading", "Chicken Breasts", "White Buns", "Pickles", "Napkins", "Receipt", "Sandwich Containers", "Bags"], custom: ["Pickles", "Lettuce", "Tomatoes","Bacon","American Cheese"]},
    { name: 'Chick-fil-A Deluxe', price: 5.55, image: 'images/entrees/CFA_Deluxe_Sandwich.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}] , ingredients: ["Breading", "Chicken Breasts", "White Buns", "Pickles", "Lettuce", "Tomatoes", "American Cheese", "Napkins", "Receipt", "Sandwich Containers", "Bags"], custom: ["Pickles", "Lettuce", "Tomatoes","Bacon","American Cheese", "Colby Jack Cheese", "Pepper Jack Cheese"]},
    { name: 'Spicy Sandwich', price: 5.25, image: 'images/entrees/CFA_Spicy_Chicken_Sandwich.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Spicy Seasoning", "Breading", "Chicken Breasts", "White Buns", "Pickles", "Lettuce", "Tomatoes", "American Cheese", "Napkins", "Receipt", "Sandwich Containers", "Bags"], custom: ["Pickles", "Lettuce", "Tomatoes","Bacon","American Cheese", "Colby Jack Cheese", "Pepper Jack Cheese"] },
    { name: 'Spicy Deluxe', price: 5.95, image: 'images/entrees/CFA_Spicy_Deluxe_Sandwich.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Spicy Seasoning", "Breading", "Chicken Breasts", "White Buns", "Pickles", "Lettuce", "Tomatoes", "Pepper Jack Cheese", "Napkins", "Receipt", "Sandwich Containers", "Bags"], custom: ["Pickles", "Lettuce", "Tomatoes","Bacon","American Cheese", "Colby Jack Cheese", "Pepper Jack Cheese"] },
    { name: 'Grilled Sandwich', price: 6.49, image: 'images/entrees/CFA_Grilled_Chicken_Sandwich.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Spicy Seasoning", "Breading", "Chicken Breasts", "White Buns", "Pickles", "Lettuce", "Tomatoes", "Napkins", "Receipt", "Sandwich Containers", "Bags"], custom: ["Pickles", "Lettuce", "Tomatoes","Bacon","American Cheese", "Colby Jack Cheese", "Pepper Jack Cheese"] },
    { name: '8 Count Nuggets', price: 4.85, image: 'images/entrees/CFA_Nuggets.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Breading" , "Chicken Breasts", "Napkins", "Receipt", "Bags"], custom: ["Ketchup", "Chick-fil-A Sauce", "Polynesian Sauce","Barbeque Sauce", "Honey Mustard Sauce" , "Garden Herb Ranch Sauce'" , "Sweet and Spicy Sriracha Sauce" ,"Honey Roasted BBQ Sauce"] },
    { name: '12 Count Nuggets', price: 6.85, image: 'images/entrees/CFA_Nuggets.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Breading" , "Chicken Breasts", "Napkins", "Receipt", "Bags"], custom: ["Ketchup", "Chick-fil-A Sauce", "Polynesian Sauce","Barbeque Sauce", "Honey Mustard Sauce" , "Garden Herb Ranch Sauce'" , "Sweet and Spicy Sriracha Sauce" ,"Honey Roasted BBQ Sauce"] },
    { name: '8 Count Grilled Nuggets', price: 5.69, image: 'images/entrees/CFA_Grilled_Nuggets.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Marination" , "Chicken Breasts", "Napkins", "Receipt", "Bags"], custom: ["Ketchup", "Chick-fil-A Sauce", "Polynesian Sauce","Barbeque Sauce", "Honey Mustard Sauce" , "Garden Herb Ranch Sauce'" , "Sweet and Spicy Sriracha Sauce" ,"Honey Roasted BBQ Sauce"] },
    { name: '12 Count Grilled Nuggets', price: 8.19, image: 'images/entrees/CFA_Grilled_Nuggets.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Marination" , "Chicken Breasts", "Napkins", "Receipt", "Bags"], custom: ["Ketchup", "Chick-fil-A Sauce", "Polynesian Sauce","Barbeque Sauce", "Honey Mustard Sauce" , "Garden Herb Ranch Sauce'" , "Sweet and Spicy Sriracha Sauce" ,"Honey Roasted BBQ Sauce"] },
];
/**
 * Information pertaining to every item on the menu, including the ingredients in the dish and modifications that can be made to them. Also includes price and a picture.
 * @type {[{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},null,null,null,null]}
 */
export const sideItems = [
    { name: 'Large Waffle Fries', price: 2.75, image: 'images/sides/CFA_Large_Fries.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: [ "Large Fry Containers" , "Sea Salt", "Waffle-Cut Potatoes", "Bags", "Napkins", "Receipt"], custom: ["Sea Salt","Ketchup", "Chick-fil-A Sauce", "Polynesian Sauce","Barbeque Sauce", "Honey Mustard Sauce" , "Garden Herb Ranch Sauce'" , "Sweet and Spicy Sriracha Sauce" ,"Honey Roasted BBQ Sauce" ] },
    { name: 'Medium Waffle Fries', price: 2.35, image: 'images/sides/CFA_Medium_Fries.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: [ "Medium Fry Containers" ,"Sea Salt", "Waffle-Cut Potatoes", "Bags", "Napkins", "Receipt"], custom: ["Sea Salt", "Ketchup", "Chick-fil-A Sauce", "Polynesian Sauce","Barbeque Sauce", "Honey Mustard Sauce" , "Garden Herb Ranch Sauce'" , "Sweet and Spicy Sriracha Sauce" ,"Honey Roasted BBQ Sauce" ]},
    { name: 'Brownie', price: 2.25, image: 'images/sides/CFA_Brownie.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Brownies", "Bags", "Napkins", "Receipt", "Dessert Bags"], custom: [] },
    { name: 'Cookie', price: 1.65, image: 'images/sides/CFA_Cookie.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Cookies", "Bags", "Napkins", "Receipt", "Dessert Bags"], custom: [] },
    { name: 'Fruit Cup', price: 3.99, image: 'images/sides/CFA_Fruit_Cup.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Small Clear Cups" ,"Plastic Forks" , "Green Apples", "Strawberries", "Blueberries", "Mandarin Oranges", "Red Apples", "Bags", "Napkins", "Receipt"] , custom: [] },
    { name: 'Greek Yogurt Parfait with Cookie Crumbs', price: 4.75, image: 'images/sides/CFA_Greek_Yogurt_Parfait_Cookie_Crumbs.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Greek Yogurt", "Cookie Crumbs", "Bags", "Napkins", "Receipt", "Plastic Spoons"], custom: [] },
    { name: 'Greek Yogurt Parfait with Granola', price: 4.75, image: 'images/sides/CFA_Greek_Yogurt_Parfait_Granola.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Granola", "Greek Yogurt", "Bags", "Napkins", "Receipt", "Plastic Spoons"], custom: [] },
    { name: 'Waffle Chips', price: 2.09, image: 'images/sides/CFA_Waffle_Chips.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Waffle Chips", "Bags", "Napkins", "Receipt"], custom: [] },
];

/**
 * Information pertaining to every item on the menu, including the ingredients in the dish and modifications that can be made to them. Also includes price and a picture.
 * @type {[{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},null,null,null,null]}
 */
export const beverageItems = [
    { name: 'Bottled Water', price: 2.25, image: 'images/beverages/CFA_Bottled_Water.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}],ingredients : ["20 Oz Dasani Water Bottles", "Receipt"] , custom: []  },
    { name: 'Fountain Drink', price: 2.19, image: 'images/beverages/CFA_Fountain_Drink.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}],ingredients : ["Lids" , "Large Red Cups", "Straws", "Receipt"] , custom: []  },
    { name: 'Large Iced Tea', price: 2.59, image: 'images/beverages/CFA_Large_Iced_Tea.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}],ingredients : ["Lids" , "Large Red Cups", "Straws" , "Tea Leaves", "Sugar", "Receipt"] , custom: ["Sugar"]  },
    { name: 'Medium Iced Tea', price: 2.19, image: 'images/beverages/CFA_Medium_Iced_Tea.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}],ingredients : ["Lids" , "Medium Red Cups", "Straws" , "Tea Leaves", "Sugar", "Receipt"] , custom: ["Sugar"]  },
    { name: 'Large Lemonade', price: 2.95, image: 'images/beverages/CFA_Large_Lemonade.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}],ingredients : ["Lids" , "Large Red Cups", "Straws" , "Lemon Juice", "Sugar", "Receipt"] , custom: ["Sugar"]  },
    { name: 'Medium Lemonade', price: 2.55, image: 'images/beverages/CFA_Medium_Lemonade.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}],ingredients : ["Lids" , "Large Red Cups", "Straws" , "Lemon Juice", "Sugar", "Receipt"] , custom: ["Sugar"]  },
    { name: 'Large Sunjoy', price: 2.95, image: 'images/beverages/CFA_Large_Sunjoy.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}],ingredients : ["Lids" , "Large Red Cups", "Straws" , "Lemon Juice", "Tea Leaves", "Sugar", "Receipt"] , custom: ["Sugar"]  },
    { name: 'Medium Sunjoy', price: 2.55, image: 'images/beverages/CFA_Medium_Sunjoy.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}],ingredients : ["Lids" , "Medium Red Cups", "Straws" , "Lemon Juice", "Tea Leaves","Sugar", "Receipt"] , custom: ["Sugar"]  },
];

/**
 * Information pertaining to every item on the menu, including the ingredients in the dish and modifications that can be made to them. Also includes price and a picture.
 * @type {[{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},null,null,null,null]}
 */
export const saladItems = [
    { name: 'Cobb Salad', price: 9.49, image: 'images/salads/CFA_Cobb_Salad.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}],
        ingredients: ["Breading", "Chicken Breasts" , "Mixed Greens" , "Bacon" ,"Monterey Jack Cheese" , "Cheddar Cheese","Eggs", "Grape Tomatoes" ,"Crispy Red Bell Pepper Seasoning", "Avocado Lime Ranch Seasoning" ,"Salad Containers" , "Plastic Forks", "Bags", "Napkins", "Receipt"],
        custom: ["Chicken Breasts" , "Mixed Greens" , "Bacon" ,"Monterey Jack Cheese" , "Cheddar Cheese", "Eggs", "Grape Tomatoes" ,"Crispy Red Bell Pepper Seasoning", "Avocado Lime Ranch Seasoning"]  },
    { name: 'Market Salad', price: 9.69, image: 'images/salads/CFA_Market_Salad.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}],
        ingredients: ["Salad Containers",  "Chicken Breasts" , "Mixed Greens" , "Red Apples" , "Green Apples" ,"Strawberries" , "Blueberries" , "Harvest Nut Granola Seasoning", "Roasted Almonds Seasoning", "Zesty Apple Cider Vinaigrette Dressing", "Bags", "Napkins", "Receipt"],
        custom: ["Chicken Breasts" , "Mixed Greens" , "Red Apples" , "Green Apples" ,"Strawberries" , "Blueberries" , "Harvest Nut Granola Seasoning", "Roasted Almonds Seasoning", "Zesty Apple Cider Vinaigrette Dressing"]  },
    { name: 'Side Salad', price: 3.79, image: 'images/salads/CFA_Side_Salad.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}],
        ingredients: [ "Plastic Forks", "Mixed Greens", "Monterey Jack Cheese" , "Cheddar Cheese", "Grape Tomatoes" , "Charred Tomato Seasoning", "Crispy Red Bell Peppers Seasoning", "Avocado Lime Ranch Seasoning", "Small Salad Containers", "Bags", "Napkins", "Receipt" ],
        custom: ["Mixed Greens", "Monterey Jack Cheese" , "Cheddar Cheese", "Grape Tomatoes" , "Charred Tomato Seasoning", "Crispy Red Bell Peppers Seasoning", "Avocado Lime Ranch Seasoning"]  },
    { name: 'Spicy Southwest Salad', price: 9.49, image: 'images/salads/CFA_Spicy_Southwest.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}],
        ingredients: ["Salad Containers" , "Chicken Breasts" , "Mixed Greens" , "Roasted Corn" ,"Monterey Jack Cheese" ,"Black Beans", "Poblano Chiles" ,"Red Bell Peppers", "Tortilla Strips", "Chili LImi Pepitas Seasoning" ,"Creamy Salsa Dressing","Plastic Forks", "Bags", "Napkins", "Receipt"],
        custom: ["Chicken Breasts" , "Mixed Greens" , "Roasted Corn" ,"Monterey Jack Cheese" ,"Black Beans", "Poblano Chiles" ,"Red Bell Peppers", "Tortilla Strips", "Chili LImi Pepitas Seasoning" , "Creamy Salsa Dressing"] },
    { name: 'Grilled Wrap', price: 7.49, image: 'images/salads/CFA_Grilled_Wrap.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}],
        ingredients: ["Bags", "Chicken Breasts" ,"Lettuce", "Monterey Jack Cheese" , "Cheddar Cheese" ,"Flaxseed Flour Flat Bread" ,"Avocado Lime Ranch Seasoning", "Bags", "Napkins", "Receipt"],
        custom: ["Chicken Breasts" ,"Lettuce", "Monterey Jack Cheese" , "Cheddar Cheese" ,"Flaxseed Flour Flat Bread" ,"Avocado Lime Ranch Seasoning" ] },
];

/**
 * Information pertaining to every item on the menu, including the ingredients in the dish and modifications that can be made to them. Also includes price and a picture.
 * @type {[{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},null,null,null,null]}
 */
export const treatItems = [
    { name: 'Chocolate Milkshake', price: 4.45, image: 'images/treats/CFA_Chocolate_Milkshake.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}],
        ingredients: ["Cream", "Cherries", "Chocolate Syrup", "Sugar", "Whipped Cream", "Medium Clear Cups", "Dome Lids" ,"2% Milk", "Straws", "Receipt"],
        custom: ["Cherries",  "Chocolate Syrup" , "Sugar", "Whipped Cream"] },
    { name: 'Cookies and Cream Milkshake', price: 4.45, image: 'images/treats/CFA_Cookies_and_Cream_Milkshake.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}],
        ingredients: ["Cream", "Chocolate Syrup", "Sugar", "Whipped Cream", "Cherries", "Oreo Cookies", "Medium Clear Cups", "Dome Lids" ,"2% Milk" , "Straws" , "Receipt"],
        custom: ["Chocolate Syrup" , "Sugar", "Whipped Cream" ,"Cherries","Oreo Cookies"] },
    { name: 'Frosted Coffee', price: 4.35, image: 'images/treats/CFA_Frosted_Coffee.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: [ "Cold-Brewed Coffee" ,"Sugar", "Medium Clear Cups", "Dome Lids" ,"2% Milk" , "Straws" , "Cream", "Receipt"], custom: ["Sugar"]  },
    { name: 'Frosted Lemonade', price: 4.35, image: 'images/treats/CFA_Frosted_Lemonade.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: [ "Lemon Juice" ,"Sugar", "Medium Clear Cups", "Dome Lids" , "Straws" , "Cream", "Receipt"], custom: ["Sugar"]   },
    { name: 'Iced Coffee', price: 3.29, image: 'images/treats/CFA_Iced_Coffee.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: [ "Cold-Brewed Coffee" ,"Sugar", "Medium Clear Cups", "Dome Lids" ,"2% Milk" , "Straws", "Receipt"], custom: ["Sugar" , "Coffee Creamers", "Vanilla Creamers"]  },
    { name: 'Strawberry Milkshake', price: 4.45, image: 'images/treats/CFA_Strawberry_Milkshake.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}],
        ingredients: ["Cream", "Cherries", "Strawberry Syrup", "Sugar", "Whipped Cream", "Medium Clear Cups", "Dome Lids" ,"2% Milk" , "Straws" , "Receipt"],
        custom: ["Cherries",  "Strawberry Syrup" , "Sugar", "Whipped Cream"] },
    { name: 'Vanilla Milkshake', price: 4.45, image: 'images/treats/CFA_Vanilla_Milkshake.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}],
        ingredients: ["Cream", "Cherries", "Vanilla Syrup", "Sugar", "Whipped Cream", "Medium Clear Cups", "Dome Lids" ,"2% Milk" , "Straws", "Receipt" ],
        custom: ["Cherries",  "Vanilla Syrup" , "Sugar", "Whipped Cream"] },
];

//ALL BELOW ITEM DO NOT NEED MODIFICATIONS
/**
 * Information pertaining to every item on the menu, including the ingredients in the dish. Also includes price and a picture.
 * @type {[{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},null,null,null,null]}
 */
export const sauceItems = [
    { name: 'Chick-fil-A Sauce', price: 0, image: 'images/sauces/CFA_Sauce.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Chick-fil-A Sauce"] , custom: [] },
    { name: 'Polynesian Sauce', price: 0, image: 'images/sauces/CFA_Polynesian.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Polynesian Sauce"], custom: []  },
    { name: 'Barbeque Sauce', price: 0, image: 'images/sauces/CFA_BBQ.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Barbeque Sauce"], custom: []  },
    { name: 'Honey Mustard Sauce', price: 0, image: 'images/sauces/CFA_Honey_Mustard.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Honey Mustard Sauce"], custom: []  },
    { name: 'Garden Herb Ranch Sauce', price: 0, image: 'images/sauces/CFA_Garden.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Garden Herb Ranch Sauce"], custom: []  },
    { name: 'Zesty Buffalo Sauce', price: 0, image: 'images/sauces/CFA_Zesty.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Zesty Buffalo Sauce"], custom: []  },
    { name: 'Sweet and Spicy Sriracha Sauce', price: 0, image: 'images/sauces/CFA_Sweet.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Sweet and Spicy Sriracha Sauce"], custom: []  },
    { name: 'Honey Roasted BBQ Sauce', price: 0, image: 'images/sauces/CFA_Honey_Roasted.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Honey Roasted BBQ Sauce"], custom: []  },
];

/**
 * Information pertaining to every item on the menu, including the ingredients in the dish and modifications that can be made to them. Also includes price and a picture.
 * @type {[{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},{image: string, price: number, custom: string[], name: string, ingredients: string[], modifications: [{changes: *[], type: string},{changes: *[], type: string}]},null,null,null,null]}
 */
export const dressingItems = [
    { name: 'Garden Herb Ranch', price: 0, image: 'images/dressings/CFA_Garden.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Garden Herb Ranch"], custom: []  },
    { name: 'Fat Free Honey Mustard', price: 0, image: 'images/dressings/CFA_Fat.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Fat Free Honey Mustard"], custom: []  },
    { name: 'Light Balsamic Vinaigrette', price: 0, image: 'images/dressings/CFA_Light_Balsamic.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Light Balsamic Vinaigrette"], custom: []  },
    { name: 'Zesty Apple Cider Vinaigrette', price: 0, image: 'images/dressings/CFA_Zesty.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Zesty Apple Cider Vinaigrette"], custom: []  },
    { name: 'Creamy Salsa', price: 0, image: 'images/dressings/CFA_Creamy.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Creamy Salsa"], custom: []  },
    { name: 'Light Italian', price: 0, image: 'images/dressings/CFA_Light_Italian.png', modifications: [{type: '+', changes: []}, {type: '-', changes: []}], ingredients: ["Light Italian"], custom: []  },
];

export const seasonalItems = [
];

getSeasonalData();